name: fresh_cart
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6 # state management tool
  get_it: ^7.7.0 # dependency injection tool
  either_dart: ^1.0.0 # error handling helper
  hive_flutter: ^1.1.0 # local database
  path_provider: ^2.1.3 # directory service helper
  internet_connection_checker_plus: ^2.5.0 #internet connection checker helper
  flutter_svg: ^2.0.10+1 # svg loader
  firebase_auth: ^5.1.1
  firebase_database: ^11.0.2
  firebase_storage: ^12.1.0
  firebase_core: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  hive_generator:
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/illustration/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/font/Poppins-ExtraLight.ttf
          weight: 200
